// <auto-generated />
using Domain.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.API.Models.Hamster", b =>
                {
                    b.Property<int>("HamsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HamsterId"), 1L, 1);

                    b.Property<string>("FavFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<int>("HamsterAge")
                        .HasColumnType("int");

                    b.Property<string>("HamsterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Loves")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("HamsterId");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            HamsterId = 1,
                            FavFood = "Seeds",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Pinokio",
                            ImgName = "hamster-1.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 2,
                            FavFood = "Carrot",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Chrome",
                            ImgName = "hamster-2.jpg",
                            Losses = 0,
                            Loves = "Jumping",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 3,
                            FavFood = "Cucumber",
                            Games = 0,
                            HamsterAge = 1,
                            HamsterName = "Firefox",
                            ImgName = "hamster-3.jpg",
                            Losses = 0,
                            Loves = "Eating",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 4,
                            FavFood = "Tomato",
                            Games = 0,
                            HamsterAge = 3,
                            HamsterName = "Safari",
                            ImgName = "hamster-4.jpg",
                            Losses = 0,
                            Loves = "Wheel",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 5,
                            FavFood = "Seed sticks",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Opera",
                            ImgName = "hamster-5.jpg",
                            Losses = 0,
                            Loves = "Running Away",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 6,
                            FavFood = "Honey",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Zebra",
                            ImgName = "hamster-6.jpg",
                            Losses = 0,
                            Loves = "Sleep",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 7,
                            FavFood = "Dirt",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Rabbit",
                            ImgName = "hamster-7.jpg",
                            Losses = 0,
                            Loves = "Dreaming",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 8,
                            FavFood = "Kefir",
                            Games = 0,
                            HamsterAge = 4,
                            HamsterName = "Elephant",
                            ImgName = "hamster-8.jpg",
                            Losses = 0,
                            Loves = "Pats",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 9,
                            FavFood = "Milk",
                            Games = 0,
                            HamsterAge = 3,
                            HamsterName = "Fly",
                            ImgName = "hamster-9.jpg",
                            Losses = 0,
                            Loves = "Walking",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 10,
                            FavFood = "Spaghetti",
                            Games = 0,
                            HamsterAge = 1,
                            HamsterName = "Horse",
                            ImgName = "hamster-10.jpg",
                            Losses = 0,
                            Loves = "Laying",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 11,
                            FavFood = "Seeds",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Pinokio",
                            ImgName = "hamster-11.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 12,
                            FavFood = "Carrot",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Chrome",
                            ImgName = "hamster-12.jpg",
                            Losses = 0,
                            Loves = "Jumping",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 13,
                            FavFood = "Cucumber",
                            Games = 0,
                            HamsterAge = 1,
                            HamsterName = "Firefox",
                            ImgName = "hamster-13.jpg",
                            Losses = 0,
                            Loves = "Eating",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 14,
                            FavFood = "Tomato",
                            Games = 0,
                            HamsterAge = 3,
                            HamsterName = "Safari",
                            ImgName = "hamster-14.jpg",
                            Losses = 0,
                            Loves = "Wheel",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 15,
                            FavFood = "Seed sticks",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Opera",
                            ImgName = "hamster-15.jpg",
                            Losses = 0,
                            Loves = "Running Away",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 16,
                            FavFood = "Honey",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Zebra",
                            ImgName = "hamster-16.jpg",
                            Losses = 0,
                            Loves = "Sleep",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 17,
                            FavFood = "Dirt",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Rabbit",
                            ImgName = "hamster-17.jpg",
                            Losses = 0,
                            Loves = "Dreaming",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 18,
                            FavFood = "Kefir",
                            Games = 0,
                            HamsterAge = 4,
                            HamsterName = "Elephant",
                            ImgName = "hamster-18.jpg",
                            Losses = 0,
                            Loves = "Pats",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 19,
                            FavFood = "Milk",
                            Games = 0,
                            HamsterAge = 3,
                            HamsterName = "Fly",
                            ImgName = "hamster-19.jpg",
                            Losses = 0,
                            Loves = "Walking",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 20,
                            FavFood = "Spaghetti",
                            Games = 0,
                            HamsterAge = 1,
                            HamsterName = "Horse",
                            ImgName = "hamster-20.jpg",
                            Losses = 0,
                            Loves = "Laying",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 21,
                            FavFood = "Seeds",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Pinokio",
                            ImgName = "hamster-21.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 22,
                            FavFood = "Carrot",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Chrome",
                            ImgName = "hamster-22.jpg",
                            Losses = 0,
                            Loves = "Jumping",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 23,
                            FavFood = "Cucumber",
                            Games = 0,
                            HamsterAge = 1,
                            HamsterName = "Firefox",
                            ImgName = "hamster-23.jpg",
                            Losses = 0,
                            Loves = "Eating",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 24,
                            FavFood = "Tomato",
                            Games = 0,
                            HamsterAge = 3,
                            HamsterName = "Safari",
                            ImgName = "hamster-24.jpg",
                            Losses = 0,
                            Loves = "Wheel",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 25,
                            FavFood = "Seed sticks",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Opera",
                            ImgName = "hamster-25.jpg",
                            Losses = 0,
                            Loves = "Running Away",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 26,
                            FavFood = "Honey",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Zebra",
                            ImgName = "hamster-26.jpg",
                            Losses = 0,
                            Loves = "Sleep",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 27,
                            FavFood = "Dirt",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Rabbit",
                            ImgName = "hamster-27.jpg",
                            Losses = 0,
                            Loves = "Dreaming",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 28,
                            FavFood = "Kefir",
                            Games = 0,
                            HamsterAge = 4,
                            HamsterName = "Elephant",
                            ImgName = "hamster-28.jpg",
                            Losses = 0,
                            Loves = "Pats",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 29,
                            FavFood = "Milk",
                            Games = 0,
                            HamsterAge = 3,
                            HamsterName = "Fly",
                            ImgName = "hamster-29.jpg",
                            Losses = 0,
                            Loves = "Walking",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 30,
                            FavFood = "Spaghetti",
                            Games = 0,
                            HamsterAge = 1,
                            HamsterName = "Horse",
                            ImgName = "hamster-30.jpg",
                            Losses = 0,
                            Loves = "Laying",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 31,
                            FavFood = "Seeds",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Pinokio",
                            ImgName = "hamster-31.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 32,
                            FavFood = "Carrot",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Chrome",
                            ImgName = "hamster-32.jpg",
                            Losses = 0,
                            Loves = "Jumping",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 33,
                            FavFood = "Cucumber",
                            Games = 0,
                            HamsterAge = 1,
                            HamsterName = "Firefox",
                            ImgName = "hamster-33.jpg",
                            Losses = 0,
                            Loves = "Eating",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 34,
                            FavFood = "Tomato",
                            Games = 0,
                            HamsterAge = 3,
                            HamsterName = "Safari",
                            ImgName = "hamster-34.jpg",
                            Losses = 0,
                            Loves = "Wheel",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 35,
                            FavFood = "Seed sticks",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Opera",
                            ImgName = "hamster-35.jpg",
                            Losses = 0,
                            Loves = "Running Away",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 36,
                            FavFood = "Honey",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Zebra",
                            ImgName = "hamster-36.jpg",
                            Losses = 0,
                            Loves = "Sleep",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 37,
                            FavFood = "Dirt",
                            Games = 0,
                            HamsterAge = 2,
                            HamsterName = "Rabbit",
                            ImgName = "hamster-37.jpg",
                            Losses = 0,
                            Loves = "Dreaming",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 38,
                            FavFood = "Kefir",
                            Games = 0,
                            HamsterAge = 4,
                            HamsterName = "Elephant",
                            ImgName = "hamster-38.jpg",
                            Losses = 0,
                            Loves = "Pats",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 39,
                            FavFood = "Milk",
                            Games = 0,
                            HamsterAge = 3,
                            HamsterName = "Fly",
                            ImgName = "hamster-39.jpg",
                            Losses = 0,
                            Loves = "Walking",
                            Wins = 0
                        },
                        new
                        {
                            HamsterId = 40,
                            FavFood = "Spaghetti",
                            Games = 0,
                            HamsterAge = 1,
                            HamsterName = "Abaddo",
                            ImgName = "hamster-40.jpg",
                            Losses = 0,
                            Loves = "Laying",
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
